# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: web
    type: git
    name: TEST/web
    trigger:
    - master
  - repository: api
    type: git
    name: TEST/api
    trigger:
    - master
  - repository: test
    type: git
    name: TEST/test
    trigger:
    - master

stages:
- stage: CI
  jobs:
  - job: CI
    steps:
      
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'install'