# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: web
    type: git
    name: TEST/web
    trigger:
    - master
  - repository: api
    type: git
    name: TEST/api
    trigger:
    - master
  - repository: test
    type: git
    name: TEST/test
    trigger:
    - master
